export const UploadFile = async ({ file }) => {
    return { file_url: `http://example.com/uploads/${file.name}` };
};

export const ExtractDataFromUploadedFile = async ({ file_url, json_schema }) => {
    return {
        status: "success",
        output: {
            data: [
                { "col1": "data1", "col2": "data2" },
                { "col1": "data3", "col2": "data4" },
            ],
            columns: ["col1", "col2"]
        }
    };
};

export const InvokeLLM = async ({ prompt, response_json_schema }) => {
    return {
        summary: "This is a summary of the data, generated by a mock AI.",
        insights: [
            "This is a key insight from the mock AI.",
            "This is another insight from the mock AI."
        ],
        data_types: {
            "col1": "string",
            "col2": "string",
        }
    };
}; 